### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/phonebook#5]
- [x] Base Import API
- [x] Base Export API
- [ ] Base Stats API
- [x] Base Search API
- [x] Auto Tags
- [ ] Polish
- [x] Tags (text only)
- [x] Fix anding
- [ ] Remove Number Mode API's
- [ ] Create Admin Menu
- [ ] Freeze Development

**Comment by krisdb2009** [comment]
Closing, and re-opening in other issues.
